baseURL: "https://domeeno.github.io/"
languageCode: "en-us"
title: "Dominic Flocea"
theme: "PaperMod"

pagination:
  pagerSize: 10
googleAnalytics: "G-YQJJ1EDL8C"
enableRobotsTXT: true

menu:
  main:
  - identifier: archive
    name: "Blog"
    url: "/posts/"
    weight: "2"
  - identifier: home
    name: "Home"
    url: "/"
    weight: "1"
  - identifier: about
    name: "About"
    url: "/about/"
    weight: "3"
  - identifier: tags
    name: "Tags"
    url: "/tags/"
    weight: "5"

params:
  env: production
  title: Dominic
  description: "Learn Programming: OOP, Distributed Systems & Programming languages"
  keywords: ["Blog", "Portfolio", "Programming", "Moldova", "Programare", "Blog"]
  author: "Dominic Flocea"
  images: []
  DateFormat: "2006, January 2"
  defaultTheme: auto
  disableThemeToggle: false

  ShowReadingTime: true
  ShowShareButtons: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  ShowWordCount: false
  ShowRssButtonInSectionTermList: true
  UseHugoToc: true
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: false
  hidemeta: false
  hideSummary: false
  showtoc: true
  tocopen: false

  social:
    - name: github
      url: "https://github.com/domeeno"
    - name:  linkedin
      url: "https://www.linkedin.com/in/dominic-flocea-227ab3206"

  analytics:
    google:
      SiteVerificationTag: "G-YQJJ1EDL8C"

markup:
  goldmark:
    renderer:
      unsafe: true # enable raw HTML in Markdown
