baseURL: "https://domeeno.github.io/"
languageCode: "en-us"
title: "Dominic Flocea"
theme: "anubis"
paginate: 10
# disqusShortname: "yourdiscussshortname"
googleAnalytics: "G-YQJJ1EDL8C"
enableRobotsTXT: true

menu:
  main:
  - identifier: archive
    name: "Blog"
    url: "/posts/"
    weight: "2"
  - identifier: home
    name: "Home"
    url: "/"
    weight: "1"
  - identifier: about
    name: "About"
    url: "/about/"
    weight: "3"
  - identifier: tags
    name: "Tags"
    url: "/tags/"
    weight: "5"


params:
  author: "Dominic Flocea"
  email: dominicflocea.dev@gmail.com # used for microformats
  # avatar: "/images/me.png" # used for microformats
  description: ""
  # Uncomment if you need this
  # images:
  #   - images/og-featured.png # relative path to "static" directory
  # customCSS:
  #   - css/my.css # relative path to "assets" directory (don't use main.css filename)
  # customJS:
  #   - js/main.js # relative path to "assets" directory
  dateFormat: "2006-01-02"
  paginationSinglePost: true
  style: light
  readMore: false
  disableSummary: false
  # utteranc.es support
  utterancesRepo: ""  # mandatory
  utterancesTheme: "" # optional
  utterancesIssue: "" # optional
  utterancesLabel: "" # optional
  webmentions:
    url: https://yourdomain.com/webemntions/receive
    login: hugo-theme-anubis
    pingback: true
  social:
  - id: github
    name: domeeno
    url: "https://github.com/domeeno"
  - id: linkedin
    name: dominic-flocea-227ab3206
    url: "https://www.linkedin.com/in/dominic-flocea-227ab3206"
  - id: twitter
    name: dominic_whtver
    url: "https://twitter.com/dominic_whtver"
#  - id: hugo
#    url: "https://gohugo.io/"
#    icon: "hugo"

markup:
  goldmark:
    renderer:
      unsafe: true # enable raw HTML in Markdown